[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "custom"
command = ''' timefor show -t '{"text": " {{if .Active}}{{else}} {{end}} {{.FormatLabel}} ", "state": "{{if .Active}}Info{{else}}Idle{{end}}"}' '''
json = true
interval = 1
[[block.click]]
button = "left"
cmd = "timefor select"

# [[block]]
# block = "tea_timer"
# format = " $icon {$minutes:$seconds |}"
# done_cmd = "notify-send 'Timer Finished'"

[[block]]
block = "custom"
command = '''echo "  $(cat ~/dotfiles/var/mailur.unread)" '''

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
format = "   $layout "
interval = 1
[[block.click]]
button = "left"
cmd = "xkb-switch -n"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# [[block]]
# block = "load"
# format = " $icon 1min avg: $1m.eng(w:4) "
# interval = 1

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired} "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:2) "

[[block]]
block = "time"
interval = 5
# format = ''' <span color="#268bd2">$timestamp.datetime(f:'%a %b %d, %R')</span> '''
format = ''' $timestamp.datetime(f:'%a %b %d, %R') '''
[[block.click]]
button = "left"
cmd = "gsimplecal"
