nm-applet: nm-applet --sm-disable
redshift: redshift-gtk -l manual:48.45205388768985:24.563229542272726
syncthing: syncthing-gtk -m
pasystray: pasystray
mate-power-manager: mate-power-manager
#xss-lock: xss-lock --transfer-sleep-lock -- i3lock --nofork
#xss-lock: xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock
stardict:  stardict -h
navidrome: navidrome -p 4533 -c ~/.config/navidrome/navidrome.toml
clipmenud: CM_SELECTIONS=clipboard clipmenud
timefor: timefor daemon --sleep-time 1s --hook "echo '<span color=\"{{if .Active}}#E69875{{else}}#7A8478{{end}}\">{{if .Active}}{{else}} {{end}} {{.FormatLabel}}</span>' > /tmp/timefor.txt; killall -USR1 i3status"
internet-check: sh -ex -c 'while true; do internet real-check && sleep 60; done'
mail: sh -ex -c 'while true; do internet check && idle-mail ~/dotfiles/var/mailur.json -t 300; done'
xkb-switch: sh -ex -c 'while true; do xkb-switch > /tmp/lang.txt; killall -USR1 i3status; xkb-switch -w; done'
