#!/bin/zsh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export EDITOR=vim
export BROWSER=chromium
export PATH="$PATH:$HOME/bin"

xset -b
setxkbmap -option "terminate:ctrl_alt_bksp"
setxkbmap -layout "us,ru(winkeys)" -option "grp:caps_toggle,grp_led:scrol"

devilspie &

(sleep 1; conky) &
volumeicon &
batti &
(sleep 1; sbxkb) &

clipit &
stardict &
tider &


DEFAULT_SESSION=startxfce4
case $1 in
  startxfce4|i3|awesome|wmfs) SESSION=$1 ;;
  *) SESSION=$DEFAULT_SESSION ;;
esac

$SESSION
