#!/bin/zsh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export PATH="$PATH:$HOME/bin"

export EDITOR=vim
export BROWSER=chromium
export TERMINAL=evilvte
export DE=xfce

xset -b
setxkbmap -option "terminate:ctrl_alt_bksp"
setxkbmap -layout "us,ru" -option "grp:caps_toggle,grp_led:caps"

case $1 in
  startxfce4|i3|awesome|wmii|wmfs) SESSION=$1;;
  *) SESSION=i3;;
esac
export SESSION
$SESSION &
PID=$!
sleep 2

if [ "$SESSION" = "startxfce4" ]; then
    devilspie &
else
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

conky &
fbxkb &
orage &
volumeicon &
batti &
clipit &
stardict &
tider &

wait $PID
